name: backend-ci
on:
  push:
jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: make up
      - run: docker compose exec app composer install
      - run: make test
